testcat:
        variables:
                GIT_SUBMODULE_STRATEGY: recursive
        script:
                - env
                - ls
                - whoami
testjob1:
        script:
                - echo Ahoj svete job1
                - echo neco > soubor.txt
        artifacts:
                paths:
                        - soubor.txt

testjob2:
        script:
                - env
                - echo test svet2

testjob3:
        script:
                - env
                - echo test svet3
