testcat:
        variables:
                GIT_SUBMODULE_STRATEGY: recursive
        script:
                - env
                - ls
                - echo Delam ze buildim
                - sleep 10
                - echo Delam ze stale buildim
                - sleep 10
                - echo Uz nedelam nic
                - sleep 10
                - echo Tak jeste neco udelam
                - sleep 10
                - whoami
testjob1:
        script:
                - echo Ahoj svete job1
                - echo neco > soubor.txt
        artifacts:
                paths:
                        - soubor.txt

testjob2:
        script:
                - env
                - echo test svet2

testjob3:
        script:
                - env
                - echo test svet3
